export const serviceActionTypes = {
  SET_SERVICE_TYPE:'SET_SERVICE_TYPE',
  ADD_TO_DROPDOWN:'ADD_TO_DROPDOWN',
  ADD_SERVICE:'ADD_SERVICE',
  REMOVE_SERVICE:'REMOVE_SERVICE',
  CLEAR_DROPDOWN:'CLEAR_DROPDOWN',
  ADD_SERVICE_TYPES:'ADD_SERVICE_TYPES',
  REMOVE_SERVICE_TYPES:'REMOVE_SERVICE_TYPES'
};
