export const UserActionTypes = {
  SET_CURRENT_USER:'SET_CURRENT_USER',
  SET_ISHOME:'SET_ISHOME',
  SET_REGISTRATION_PROGRESS:'SET_REGISTRATION_PROGRESS',
  SET_USER_TYPE:'SET_USER_TYPE',
  SET_REGISTERED_USERID:'SET_REGISTERED_USERID',
  SET_SUBSCRIPTION_TYPE:'SET_SUBSCRIPTION_TYPE',
  SET_INDIVIDUAL_SUB:'SET_INDIVIDUAL_SUB'
};
